# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: "2021-08-15T12:51:31Z"
  generation: 2
  labels:
    app: canarybear
  name: canarybear
  namespace: default
  resourceVersion: "73992"
  selfLink: /apis/apps/v1/namespaces/default/deployments/canarybear
  uid: 59ec29fd-3a26-4baf-a96d-ebce1e678788
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: canarybear
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: canarybear
    spec:
      containers:
      - image: supergiantkir/animals:bear
        imagePullPolicy: Always
        name: canary
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2021-08-11T12:51:31Z"
    lastUpdateTime: "2021-08-11T12:51:34Z"
    message: ReplicaSet "canaryBear" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  - lastTransitionTime: "2021-08-11T12:52:35Z"
    lastUpdateTime: "2021-08-11T12:52:35Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 2
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
