apiVersion: v1
kind: Pod
metadata: 
 name: nginx 
spec:
 containers:
 - name: nginx 
   image: nginx:1.7.9 
   volumeMounts:
   - name: app-storage
     mountPath: /storage
   ports: 
   - containerPort: 80
 - name: app2
   image: yanivomc/spring-music:latest
   volumeMounts:
   - name: app-storage
     mountPath: /storage
   ports: 
   - containerPort: 8080
 - name: app1
   image: supergiantkir/animals:bear
   ports:
   - containerPort: 8081
  volumes:
  - name: app-storage
    emptyDir: {}
